### ISSUE TITLE
Move the Direction enum inside a class/namespace

### ISSUE THREAD

**Issue by dkopecek** [radosroka/usbmon#2]
The Direction enumeration values might conflict with third-party code. The enum could be moved inside the Usbpacket class and the values will then be referenced with the class name prefix, i.e. Usbpacket::BOTH instead of just BOTH. Or scoped enumeration (C++11) could be used, see "Scoped Enumeration" at http://en.cppreference.com/w/cpp/language/enum.

https://github.com/radosroka/usbmon/blob/master/usbpacket.hpp#L45

**Comment by radosroka** [comment]
I added namespaces in commit fed49754266175f953c19458b5d6cb469f3bb4d9.
