### ISSUE TITLE
Document usage of magic constants in the code

### ISSUE THREAD

**Issue by dkopecek** [radosroka/usbmon#3]
The usage of magic in the code is neither referenced to an URL explaining them nor documented using a comment. Please document places in the code like these:
- https://github.com/radosroka/usbmon/blob/master/usbmon.cpp#L214 (why the doubling with `* 2`?)
- https://github.com/radosroka/usbmon/blob/master/usbpacket.cpp#L48 (why is 0x80 so special?)

**Comment by radosroka** [comment]
It's resolved. b11c0f362ed39c643e107ea693812bd64d4067ca
