### ISSUE TITLE
Use statically allocated memory in Usbmon::loop()

### ISSUE THREAD

**Issue by dkopecek** [radosroka/usbmon#4]
A packet object and a data buffer is allocated for each iteration of the look at https://github.com/radosroka/usbmon/blob/master/usbmon.cpp#L63 and #L64. Dynamically allocating these objects on the heap seems unnecessary and the code handling the deallocation isn't exception-safe. You could instead statically allocate these objects and reuse them in the loop (and maybe reset them for each iteration of the loop).

**Comment by radosroka** [comment]
I did some optimalization in commit 8b036a6da617741baf87c5ff3c58626cdf4948ac.
